config/routes.rb
Rainforest::Application.routes.draw do
  get "reviews/show"
  get "reviews/new"
  get "reviews/edit"
  # delete "/products/:product_id/reviews/:id", to "reviews#destroy", as: "review_delete"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  resources :products do
    resources :reviews, :except => [:index, :show]
  end
  root :to => "products#index"

  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
end


  

app/models/picture.rb
class Picture < ActiveRecord::Base
	  def image_file=(input_data)
    self.filename = input_data.original_filename
    self.content_type = input_data.content_type.chomp
    self.binary_data = input_data.read
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
	before_save :convert_to_cents

  validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => true
  has_many :pictures
  has_many :reviews
  has_many :users, :through => :reviews
  mount_uploader :picture, PictureUploader



  def convert_to_cents
  	self.price_in_cents = (self.price_in_cents.to_f*100).to_i
  end

  def formatted_price
    (self.price_in_cents.to_f / 100).to_s(:currency)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  validates_uniqueness_of :user_id, :scope => [:product_id] #allows a user to only comment on a product once
  validates :comment, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name
  validates :email, :uniqueness => true
  has_secure_password
  validates_presence_of :password, :on => :create
  has_many :reviews
  has_many :products, :through => :reviews
  has_many :pictures, :through => :products
  # has_one :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :ensure_logged_in, :only => [:show, :new]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
   def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end


  # GET /products/new
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price_in_cents, :user_id, :picture)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_product
  before_filter :ensure_logged_in, :only => [:edit, :create, :show, :update, :destroy]

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user_id = current_user.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to product_path(@product.id), notice: 'Review created successfully' }
        format.js {} # This will look for /views/reviews/create.js.erb
      else
        format.html { render "products/show", notice: 'You have already made a review on this product!'  }
        format.js {} # This will look for /views/reviews/create.js.erb
      end
    end

  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@product)
  end

  private

  def load_product
    @product = Product.find(params[:product_id])
  end

  def review_params
    params.require(:review).permit(:comment, :user_id, :product_id, :name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # start a new session
      session[:user_id] = @user.id
      redirect_to products_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="header">
      <div class="logo"><%= link_to "Rainforest", root_path %></div> 
      <p class="userinfo">  
        <% if current_user %>
          Signed in as <%= current_user.name %> | <%= link_to "Log out", session_path("current"), :method => :delete %>
        <% else %>
          <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
        <% end %>
      </p> 
    </div>

    <div id="wrapper">
      <% if flash[:notice] %>
        <p id="notice"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p id="alert"><%= flash[:alert] %></p>
      <% end %>

      <%= yield %>

      
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.text_field :price_in_cents %>
  </div>
  <% if @product.picture == "" %>
  <div class ="field">
    <%= f.file_field :picture %>
    <%= f.hidden_field :picture_cache %>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
      <%if @product.picture != "" %>
        <%= image_tag @product.picture %>
        <%= f.check_box :remove_picture %>
        Remove Picture?
      <% end %>
<% end %>

app/views/products/_review_form_errors.html.erb
<% if @review.errors.present? %>
  <% @review.errors.full_messages.each do |error| %>
    <div class="alert">
      <%= error %>
    </div>
  <% end %>
<% end %>

app/views/products/_reviews.html.erb
<% @product.reviews.each do |review| %>
  <p>
    <%= review.comment %>
    <br>
    <% if review.user != nil %>
      <em> by <%= review.user.name %></em>
      Added on: <%= review.created_at %>
    <% end %>

    <% if review.user == current_user %>
    	<%= button_to "delete", product_review_path(@product, review), :action => 'destroy', :method => :delete, :confirm => "Are you sure you want to do that?" %>
    	
    <% end %>

  </p>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Your Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
  <% @products.each do |product| %>   
    <div class="product_item">
      <p><%= link_to product.name, product_path(product) %></p>
    </div>
  <% end %>

<%= link_to 'Add A New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1 class="item_name shadowed"><%= @product.name %></h1>
<h3><%= @product.formatted_price %></h3>
<p><h4><%= @product.description %></h4></p>
<img src="<%= @product.picture %>">


<% if current_user %>
	<div class="reviews">
	  <h3>Reviews</h3>

	  <p>Reviews for <%= @product.name %></p>

	  <div id="review-list">
		  <%= render :partial => "products/reviews" %>
	  </div>

		<% unless current_user.reviews.where(product_id: @product.id).any? %>
			<h4>New Review</h4>

			 <%= form_for [@product, @review], :remote => true do |f| %>

			  <div id="review-form-errors">
			    <%= render :partial => "/products/review_form_errors" %>
				</div>

			    <div class="field">
			      <%= f.label :comment %><br />
			      <%= f.text_area :comment %>
			    </div>
			    <div class="actions">
			      <%= f.submit %>
			    </div>

			  <% end %>
		<% end %>

		<% else %>
	  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p> 
	</div>
<% end %>


<h5>
<tr>
	<td><%= link_to 'Edit', edit_product_path(@product) %></td> |
	<td><%= link_to 'Back', products_path %></td> |
	<td><%= link_to 'Delete this item', @product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
</h5>

<script type="text/javascript">
  $(function() {
     $("#new_review")
        .bind('ajax:beforeSend', function() { # set this code to happen just before the ajax request is made
          $("input[type='submit']") # make changes to the submit button
            .val('Saving...') # change the text on the button
            .attr('disabled', 'disabled'); # disable the button
        })
        .bind('ajax:complete', function() {
          $("input[type='submit']")
            .val('Create Review')
            .removeAttr('disabled');
        });
  });
</script>

app/views/reviews/create.js.erb
<% if @review.errors.present? %>
  $("#review-form-errors").html("<%= escape_javascript(render(:partial => '/products/review_form_errors')) %>");
<% else %>
  $("#review-form-errors").html("");
  $("#review-list").html("<%= escape_javascript(render(:partial => '/products/reviews')) %>");
  $("#new_review")[0].reset();
<% end %>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>